name: service
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
    - name: Zip output
      uses: papeloto/action-zip@v1
      with:
        files: src/main.exe src/main.pdb
        dest: investager-service.zip
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: investager-service
        path: investager-api.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: investager-service
      - name: Copy artifact
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          source: "investager-service.zip"
          target: "/home/investager"
      - name: Upgrade
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            systemctl stop investager-api
            cd /home/investager
            zip -r "$(date +%Y%m%d_%H%M%S)_service.zip" service/
            rm -rf service
            unzip investager-service.zip -d service
            rm investager-service.zip
            systemctl start investager-api
